
name: Code Coverage
on:
  push:
    branches:
      - 'master'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install -r requirements/release.txt
      - name: Generate Code Coverage Report
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload Report to <codecov.io>
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
